### ISSUE TITLE
No tiles request on Firefox with IDN domain name

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/ol3#110]
Via geoadmin-api mailing list:

I registered my domain, received the confirmation e-mail and copied your "API Quick start" example on this URL:

http://www.françois.ch/maps/example.htm

On Chrome, Safari and IE it works fine, but in Firefox (both Mac and Windows) I get a blank map. Is this a bug from Firefox or GeoAdmin API, that doesn't handle accented domain names? Note the cedilla in my domain name.

Tested with latest version of Firefox on latest OS version:
- Firefox 32.0.2 on Mac OS X 10.9.5
- Firefox 32.0.2 on Windows 8.1 Pro

I did check on the S3, there is effectively no request for tiles with  these settings. The API files (html, js and css) are correctly handled though.

**Comment by cedricmoullet** [comment]
Browser issue
