### ISSUE TITLE
search by lat/lon coordinates

### ISSUE THREAD

**Issue by phrixothrixa** [geoadmin/ol3#149]
Hello! How can I get building information with api3.geo.admin.ch/rest/services/api/SearchServer endpoint with lat/lon coordinates? Can I convert lat/lon to bbox for it somehow?

**Comment by davidoesch** [comment]
Use the GeoAdmin API Forum to ask questions: http://groups.google.com/group/geoadmin-api  regrading api.
TL;DR: lat lon you have to convert them to LV03 or LV95 and use the identify interface https://api3.geo.admin.ch/services/sdiservices.html#id11 and use the dataset ch.bfs.gebaeude_wohnungs_register

**Comment by davidoesch** [comment]
and of course lat long is supported by the identify service 

sr (optional) | The spatial reference. Supported values: 21781 (LV03), 2056 (LV95), 4326 (WGS84) and 3857 (Web Pseudo-Mercator). Defaults to “21781”.
-- | --
